#spring:
#  profiles:
#    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://yafwhodb.cnzl0t4lkvdi.eu-central-1.rds.amazonaws.com:5432/postgres
    username: //?
    password: //?
    pool-size: 30